version: "3.2"
services:
  rabbitmq-go:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-go'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq-go/data/:/var/lib/rabbitmq-go/
        - ~/.docker-conf/rabbitmq-go/log/:/var/log/rabbitmq-go
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
